[server]
runOnSave = true

[browser]
gatherUsageStats = false


[runner]
magicEnabled = true

[logger]
level = "info"

[theme]
base = "light"

[global]
developmentMode = false

[layout]
showSidebarNavigation = true
centerWidgets = false

[client]
caching = true
displayEnabled = true
showErrorDetails = true
toolbarMode = "auto"
layout = "wide" 
showSidebar = true